name: Gradle Build
on: [push, pull_request]

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm ci
    - run: ./gradlew build -s
